TITLE: Caelins Idylle #Blog title
URL: 'https://caelinaraven.netlify.app/' # Blog url, we use it to generate sitemap
BASE: '' # Blog base folder is any, most of the timme just ''
DESCRIPTION: Caelins Dev Blog # Blog descriptioj
LANG: EN # Blog language
DATE_LANG: fr # Blog date format fr for dd/mm/yyyy en-US for mm/dd/yyyy
STYLE: sans # Defaut blog style sans | serif | sans-and-serif | serif-and-sans
AUTHOR: Caelin Araven # Author name
CONTACT: true # Set to false to omit email/contact link in header
EMAIL: Thomasvangrol@email.com # Email
POST_COVER: true # Show post cover in post page
# MY_SWITCH: true #uncomment to add additional link to header.
# MY_LINK: https://link.to.something #copy structure for further links.
# Edit also relevant parts in 'src/types/config.d.ts' and 'src/components/header.astro'.
POST_THUMBNAILS: true # Show post cover in lists of posts 
POST_SUGGESTIONS: true # Suggest more posts to read based on tags
HOME_NB_POSTS: 6 # Number of posts to show on the home page
MENU: # Main menu 
  - label: RSS # Example menu label
    url: rss.xml # Example menu url
  - label: Archive # Example menu label
    url: archive # Example menu url
  - label: Blogroll # Example menu label
    url: blogroll # Example menu url
  - label: Editor # Example menu label
    url: editor # Example menu url
BLOG_COVER:  # Blog cover for social networks previews
  src: Nature of things.jpg # Cover url (must be placed in the folder src/public)
  alt: Nature of Things # Cover image alt text, mandatory
BANNER: # Blog banner, appears above the menu if any
  src:  # Banner url (must be placed in the folder src/media)
  alt:  # Banner image alt text, mandatory
EDITOR:
  GITHUBUSER: Thomasvangrol # Github user name
  GITHUBREPO: Thomasvangrol # Github repo
